@url = http://localhost:3000

# ==================== CARTEIRAS E CONTAS ====================

### Buscar carteiras e contas
GET {{url}}/carteira-has-conta
### Criar carteiraHasConta
POST {{url}}/carteiraHasConta
Content-Type: application/json  

{
  "id_carteira": 1,
  "id_conta": 1
}

