ALTER TABLE transacao
  ADD COLUMN IF NOT EXISTS id_carteira INT REFERENCES carteira(id_carteira) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS arquivado BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE transacao SET arquivado = FALSE WHERE arquivado IS NULL;
ALTER TABLE transacao ALTER COLUMN arquivado SET DEFAULT FALSE;
ALTER TABLE transacao ALTER COLUMN arquivado SET NOT NULL;